# Generated by Django 4.1.6 on 2023-02-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sueldo', '0001_initial'),
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jubilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('numero', models.CharField(max_length=240)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'FEMENINO')], max_length=20)),
                ('aplicacion_sueldo', models.IntegerField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.cuenta')),
                ('sueldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueldo.sueldo')),
            ],
        ),
    ]
