# Generated by Django 4.1.6 on 2023-02-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jubilado', '0005_jubilado_tipo_jubilacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descuento', models.CharField(max_length=240, null=True)),
                ('periodo', models.CharField(max_length=240)),
                ('jubilado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jubilado.jubilado')),
            ],
        ),
    ]
