# Generated by Django 4.1.6 on 2023-02-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilado', '0007_alter_liquidacion_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='total',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
