# Generated by Django 4.1.6 on 2023-02-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jubilado', '0009_alter_liquidacion_jubilado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='jubilado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jubilado.jubilado'),
        ),
    ]
