# Generated by Django 4.1.6 on 2023-02-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu', models.IntegerField()),
                ('cuenta', models.IntegerField()),
                ('tipo', models.CharField(choices=[{'codigo': '02', 'tipo': 'CC'}, {'codigo': '01', 'tipo': 'CA'}], max_length=9)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.banco')),
            ],
        ),
    ]
