# Generated by Django 4.1.6 on 2023-02-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_cuenta_cbu_alter_cuenta_cuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='banco',
        ),
    ]
