# Generated by Django 4.1.6 on 2023-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cbu',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('01', 'CC'), ('02', 'CA')], max_length=9),
        ),
    ]
