# Generated by Django 4.1.6 on 2023-02-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jubilado', '0003_jubilado_banco_jubilado_cbu_jubilado_tipo_cuenta_and_more'),
        ('cuenta', '0003_remove_cuenta_banco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
