# Generated by Django 4.1.6 on 2023-02-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_delete_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
