# Generated by Django 4.1.6 on 2023-02-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
