# Generated by Django 4.1.6 on 2023-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jubilado',
            name='sexo',
            field=models.CharField(choices=[('01', 'FEMENINO'), ('02', 'MASCULINO')], max_length=20),
        ),
    ]
