# Generated by Django 4.1.6 on 2023-02-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_remove_cuenta_banco'),
        ('jubilado', '0002_alter_jubilado_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jubilado',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.banco'),
        ),
        migrations.AddField(
            model_name='jubilado',
            name='cbu',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='jubilado',
            name='tipo_cuenta',
            field=models.CharField(choices=[('01', 'CC'), ('02', 'CA')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='jubilado',
            name='cuenta',
            field=models.CharField(max_length=240),
        ),
    ]
