# Generated by Django 4.1.6 on 2023-02-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilado', '0003_jubilado_banco_jubilado_cbu_jubilado_tipo_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jubilado',
            name='sexo',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], max_length=20),
        ),
    ]
