# Generated by Django 4.1.6 on 2023-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilado', '0004_alter_jubilado_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jubilado',
            name='tipo_jubilacion',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
